#!/bin/bash

args=$@
echo $args
echo -n backup name\:  
read name

echo
echo "  packing..."
sleep 0.5
echo "  compressing..."
tar -czf $name.tar $args

echo
gzip -l $name.tar
mv $name.tar ~/Backup/$name.tar.gz

echo
echo "  saved as: ~/Backup/$name.tar.gz"
echo
